In [ ]:
import numpy as np      #dot multiplication
A=np.array([[1,2],[3,4]])
B=np.array([[5,6,7],[7,8,8]])

print(A@B)


[[19 22 23]
 [43 50 53]]


In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=np.dot(A,B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A*B)


[[ 5 12]
 [21 32]]


In [ ]:
matrix=np.array([[1,2,3],[4,4,5]])
transposed=matrix.T
print(matrix)
print(transposed)
#print(np.transpose(matrix))

[[1 2 3]
 [4 4 5]]
[[1 4]
 [2 4]
 [3 5]]


In [ ]:
import numpy as np
matrix1=np.array([2])
matrix2=np.array([[2,3],[3,3]])
matrix3=np.array([[[2,3,4],[2,4,5],[4,5,7]]])
det=np.linalg.det(matrix3)
print("\n",matrix1)
print("\n",matrix2)
print("\n",matrix3)
print("\n",det)


 [2]

 [[2 3]
 [3 3]]

 [[[2 3 4]
  [2 4 5]
  [4 5 7]]]

 [0.]


In [ ]:
import numpy as np
matrix1=np.array([2])
matrix2=np.array([[2,3],[3,3]])
matrix3=np.array([[[2,3,4],[2,9,5],[4,5,8]]])
inverse=np.linalg.inv(matrix3)
print(inverse)
rank =(np.linalg.matrix_rank(matrix1))
print(rank)

[[[ 2.35000000e+01 -2.00000000e+00 -1.05000000e+01]
  [ 2.00000000e+00 -5.46571335e-16 -1.00000000e+00]
  [-1.30000000e+01  1.00000000e+00  6.00000000e+00]]]
1


In [ ]:
matrix3=np.array([[[2,3,4],[2,9,5],[4,5,8]]])
eigenvalues,eigenvectors=np.linalg.eig(matrix3)
print(eigenvalues)
print("\n",eigenvectors)

[[15.10200257  0.03427596  3.86372147]]

 [[[-0.35353693 -0.87100921  0.23161245]
  [-0.65947264 -0.07634343 -0.72337648]
  [-0.66340597  0.48529851  0.65044764]]]


In [ ]:
import numpy as np
A=([[2,3],[4,5]])
b=([[6,9],[8,10]])
solution=np.linalg.solve(A,b)
print(solution)

[[-3.  -7.5]
 [ 4.   8. ]]
