In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
import numpy as np
arr=np.array((2,3,4,7))
print(arr)

[2 3 4 7]


In [ ]:
import numpy as np
arr=np.array((2.1,32,32.3,2.3))
print(arr)
max=np.max(arr)
print(max)
min=np.min(arr)
print(min)

[ 2.1 32.  32.3  2.3]
32.3
2.1


In [ ]:
import numpy as np
arr=np.array([2.3,32,32.3,2.3])
print(arr)
print(arr.dtype)

[ 2.3 32.  32.3  2.3]
float64


In [ ]:
import numpy as np
arr=np.array(("snj",'sd','isji'))
print(arr)
print(arr.dtype)

['snj' 'sd' 'isji']
<U4


In [15]:
import numpy as np
arrr=np.array(3)
print(arrr)
arr=np.array([2.3,32,32.3,2.3])
print(arr)

ar=np.array(((2,23),(2,33)))
print(ar*2)

r=np.array([[[2,3,4],[23,23,2]],[[0,87,76],[2,32,2]]])
print(r)
sum=np.sum(r)
print("sum of numbers:",sum)


print(arrr.ndim,arr.ndim,ar.ndim,r.ndim,)

3
[ 2.3 32.  32.3  2.3]
[[ 4 46]
 [ 4 66]]
[[[ 2  3  4]
  [23 23  2]]

 [[ 0 87 76]
  [ 2 32  2]]]
sum of numbers: 256
0 1 2 3


In [ ]:
import numpy as np
arr=np.array([1,23,4,5],ndmin=6)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[[ 1 23  4  5]]]]]]
number of dimensions: 6


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[3])
print(arr[2]+arr[1])

4
5


In [ ]:
import numpy as np
zeros=np.zeros((5,4))
ones=np.ones((3,4))
range_arr=np.arange(1,9,20)
linspace=np.linspace(1,3,6)
identity=np.eye(4)
random_arr=np.random.rand(4,3)

print("\n",zeros)
print("\n",ones)
print("\n",range_arr)
print("\n",linspace)
print("\n",identity)
print("\n",random_arr)


 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [1]

 [1.  1.4 1.8 2.2 2.6 3. ]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[0.32427264 0.20876649 0.71270156]
 [0.74026114 0.07267211 0.06601579]
 [0.80581126 0.46119074 0.37796021]
 [0.53840303 0.12687581 0.2032499 ]]


In [ ]:

import numpy as np
crop_yields=np.array([
    [12.3,33.3,43.4,34.4,12.5],
    [10.23,12.12,92.2,1.2,7.1],
    [12.2,12.23,21.4,34.3,34.2],
    [12.13,12.2,12,23.2,12]
])

print('Crop Yields Array(Tons):')
print(crop_yields)
print(f'\nShape:{crop_yields.shape}')
print(f'\nDataType: {crop_yields.dtype}')
print(f'\nTotal Elements:{crop_yields.size}')
print(f'\nNumber of dimensions:{crop_yields.ndim}')


total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season= np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\nTotal Production: {total_yield}Tons')
print(f'\nAverage per farm:{avg_yield_per_farm}Tons')
print(f'\nAverage per season:{avg_yield_per_season}Tons')
print(f'\nMaxium yield:{max_yield}Tons')
print(f'\nMinimum yield:{min_yield}Tons')


best_farm=np.argmax(avg_yield_per_farm)
print(f'\nBest Performing Farm:farm{best_farm+1}')
print(f'\nTheir average yield:{avg_yield_per_farm[best_farm]:.2f}Tons')

Crop Yields Array(Tons):
[[12.3  33.3  43.4  34.4  12.5 ]
 [10.23 12.12 92.2   1.2   7.1 ]
 [12.2  12.23 21.4  34.3  34.2 ]
 [12.13 12.2  12.   23.2  12.  ]]

Shape:(4, 5)

DataType: float64

Total Elements:20

Number of dimensions:2

Total Production: 444.61Tons

Average per farm:[27.18  24.57  22.866 14.306]Tons

Average per season:[11.715  17.4625 42.25   23.275  16.45  ]Tons

Maxium yield:92.2Tons

Minimum yield:1.2Tons

Best Performing Farm:farm1

Their average yield:27.18Tons


In [ ]:
import numpy as np
A=np.array([23,356,7,7,34,24,77,39,23,8])
print(A)
np.sort(A)

[ 23 356   7   7  34  24  77  39  23   8]


array([  7,   7,   8,  23,  23,  24,  34,  39,  77, 356])

In [ ]:
np.argsort(A)

array([3, 2, 9, 0, 8, 5, 4, 7, 6, 1])

In [16]:
a=np.array([[2,34],[932,2]])
b=np.array([[3,32],[232,23]])
c=([3])
print(np.concatenate((a,b),axis=0))
#print("\n\n\n")
print(np.concatenate((a,b),axis=1))

[[  2  34]
 [932   2]
 [  3  32]
 [232  23]]
[[  2  34   3  32]
 [932   2 232  23]]


In [ ]:
a=np.array([[2,34],[932,2]])
b=np.array([[[3,32],[232,23]],[[243,45],[324,43]]])
print(b.ndim)
np.concatenate((a,b),axis=0)

3


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [20]:
a=np.arange(2,30,5)
print(a)
b=a.reshape(3,2)
print(b)

[ 2  7 12 17 22 27]
[[ 2  7]
 [12 17]
 [22 27]]


In [22]:
b=np.array([ 2,7,12, 17, 22, 27])
print(b[0:])
print(b[-1:])
print(b[2:7])

[ 2  7 12 17 22 27]
[27]
[12 17 22 27]


In [ ]:
c=np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])
print(c)
print(c[c<8])
print("\n\n")
print("8 up:",c[c>8])
print("\n")
print(c[(c > 8) & (c < 13)])
print("\n\n")
divisible_by_3=c[c%3==0]
print(divisible_by_3)
print("\n\n")
six_up=(c>6)|(c==6)
print(six_up)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[2 3 4 5 6 7]



8 up: [ 9 10 11 12 13]


[ 9 10 11 12]



[ 3  6  9 12]



[[False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
data=np.array([[[2.23,323],[23.3,253]],[[213,233],[32,3]]])
data*2.34


array([[[  5.2182, 755.82  ],
        [ 54.522 , 592.02  ]],

       [[498.42  , 545.22  ],
        [ 74.88  ,   7.02  ]]])

In [ ]:
b=[[12,23,2],[23,323,23]]
data*b

ValueError: operands could not be broadcast together with shapes (2,2,2) (2,3) 

In [ ]:
import numpy as  np
yields=np.array([
    [45,48,52,49,53],
    [38,41,39,44,42],
    [52,55,58,56,60],
    [41,43,45,47,46]

])
weather_factors=np.array([1,0.95,1.05,0.98,1.02])
print('Original Yields(Tons/hectare):')
print(yields)
print('\nWeather Impact Factors:',weather_factors)
adjusted_yields=yields*weather_factors
print('\nWeather-Adjusted Yields')
print(adjusted_yields)
exceptional=adjusted_yields>55
print('\nExceptional yields(>55):')
print(adjusted_yields[exceptional])
categories=np.where(
    adjusted_yields>50,'high',
    np.where(adjusted_yields>40,'medium','low'))

print('\nYield Categories:')
print(categories)

selected_farms=[0,2]
print(f'\nSelected Farm Yields:')
print(yields[selected_farms])

good_years=adjusted_yields[(adjusted_yields>45)&(adjusted_yields<55)]
print(f'\nGood Performing Years(45-55Tons):')
print(good_years)




Original Yields(Tons/hectare):
[[45 48 52 49 53]
 [38 41 39 44 42]
 [52 55 58 56 60]
 [41 43 45 47 46]]

Weather Impact Factors: [1.   0.95 1.05 0.98 1.02]

Weather-Adjusted Yields
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

Exceptional yields(>55):
[60.9 61.2]

Yield Categories:
[['medium' 'medium' 'high' 'medium' 'high']
 ['low' 'low' 'medium' 'medium' 'medium']
 ['high' 'high' 'high' 'high' 'high']
 ['medium' 'medium' 'medium' 'medium' 'medium']]

Selected Farm Yields:
[[45 48 52 49 53]
 [52 55 58 56 60]]

Good Performing Years(45-55Tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]


In [ ]:
import numpy as np
a=np.arange(50).reshape(10,5)
print("original array(10x5):\n",a)
print(a[:,0])
print(a[:1])
print(a[:,2])
print(a[3,:])
selected_rows=a[a[:,0]>20]
print("\nRows where first feature>20:\n",selected_rows)

original array(10x5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 0  5 10 15 20 25 30 35 40 45]
[[0 1 2 3 4]]
[ 2  7 12 17 22 27 32 37 42 47]
[15 16 17 18 19]

Rows where first feature>20:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
