In [71]:
import numpy as np
a=np.array([32,43,42,54,54])
b=np.array([3,0,4,1])
print(a[b])

[54 32 54 43]


In [72]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[:,1]%2==0])

[[1 2]
 [3 4]
 [5 6]]


In [73]:
a=np.array([[1,3],[3,4]])
b=np.array([10,20,30])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [75]:
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([True,False,True])
print(a[mask])

[[1 2]
 [5 6]]


In [74]:
a=np.arange(6)
c=a.reshape(2,3)
b=np.arange(3)
d=b.reshape(3,)
print(c)
print(d)
print(c+d)
print(c*d)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 2 4]
 [3 5 7]]
[[ 0  1  4]
 [ 0  4 10]]


In [76]:
a=np.array([0.5,2,3,4,5])
print(a.shape)
print([a>0.5])
print(a>0)
print(a[a>=0.5])

(5,)
[array([False,  True,  True,  True,  True])]
[ True  True  True  True  True]
[0.5 2.  3.  4.  5. ]


In [77]:
arr=np.array([[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]])
mask=np.array([[True,False,True]])
print(arr[mask])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [78]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[:,[False,True]])
print(a[[False,True,False]])
print(a[:,0])

[[1 2]
 [3 4]
 [5 6]]
[[2]
 [4]
 [6]]
[[3 4]]
[1 3 5]


In [79]:
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([True,True,False])
b=a[mask]*10
print(b)

[[10 20]
 [30 40]]


In [80]:
x=np.arange(10)
b=x.reshape(5,2)
print(b)
print(b[::3])


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [6 7]]


In [81]:
a=np.array([[1,2],[2,3],[4,4]])
mask=np.array([False,True,False])
print(a[mask])

[[2 3]]
